#!/usr/bin/env ruby

class Source
  FUNCTIONS = %w{import}

  def initialize(source)
    @source = source
  end

  
  def import(filename, syntax = nil)
    filename = @root_dir + '/' + filename if @root_dir

    puts "importing #{filename} #{syntax && "with syntax: #{syntax}"}"

    data = syntax ? "#{@indent}:::#{syntax}\n" : ''
    data << File.read(filename).lines.map { |l| @indent.to_s + l }.join
    Source.new(data).to_devcenter(File.dirname(filename))
  end

  def to_devcenter(root_dir = nil)
    @root_dir = root_dir
    @source.dup.tap do |output|
      FUNCTIONS.each do |f| 
        function_call = /( *)\!#{f}\(([^\)]+)\)/
        output.gsub!(function_call) do |token|
          matchdata = token.match(function_call)
          @indent = matchdata[1]
          send(f, *matchdata[2].split(','))
        end
      end
    end
  end
end

puts Source.new(File.read(ARGV[0])).to_devcenter
