#!/usr/bin/env ruby

class Source
  FUNCTIONS = %w{import}

  def initialize(source)
    @source = source
  end

  def import(file, syntax = nil)
    if syntax
      data = ":::#{syntax}\n" 
      data << File.read(file).lines.map { |l| "    #{l}" }.join("\n") 
    else
      data = File.read(file)
    end

    Source.new(data).to_devcenter
  end

  def to_devcenter
    @source.dup.tap do |output|
      FUNCTIONS.each do |f| 
        function_call = /\!#{f}\(([^\)]+)\)/
        output.gsub!(function_call) do |token|
          matchdata = token.match(function_call)
          send(f, *matchdata[1].split(','))
        end
      end
    end
  end
end

puts Source.new(File.read(ARGV[0])).to_devcenter
