#!/usr/bin/env ruby

require 'restclient'

email     = 'csquared@heroku.com'
password  = 'password'
url       = 'http://localhost:3000'
resource  = RestClient::Resource.new(url)

login_response = resource['/admin/session'].post(
  {:typus_user => {:email => email, :password => password}}
) { |response, request, result| response }

session = login_response.cookies

puts resource['/admin/articles/create'].post(
  {:article => {
    :title => "Hello, World",
    :content => "this was almost too easy",
    :status => 'draft',
    :category_id => '1'
  }},
  :cookies => session, :accept => :html
) { |response, request, result| response }


